### ISSUE TITLE
Pin API and UI image refs in released operator images

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/eda-server-operator#125]
There are no gaurantees that newer api and ui images will be compatible with a given released eda-server-operator image.  We should pin the latest api and ui image at time of release inside the operator image as env vars.  

Here is how it was done in AWX Operator:
* https://github.com/ansible/awx-operator/pull/612/files

We will need to coordinate with the eda-server and eda-ui image maintainers to standardize tags as needed.  We will also want to write a release script or GHA that accepts a version or image tags as inputs.

**Comment by Daniel-Vaz** [comment]
Regarding this issue I think that also currently a high priority is make sure the `eda-server-operator` has a tag that is stable and is working with the latest `eda-ui` and `eda-server` images. 

From my testing currently in order to not use the "latest"\"main" versions of all these 3 images, we can only use the `eda-server-operator` tag `0.0.4`, and because of these issues ([UI ](https://github.com/ansible/eda-server-operator/issues/123#issue-1852457286)\ [Server](https://github.com/ansible/eda-server-operator/issues/111#issuecomment-1665232248)), we can only use the image older and specific image tags.

Based on the recent worker CRD changes I believe it would be crucial to have a version `0.0.5` of the eda-server-operator stable enough with some statically defined `eda-server` and `eda-ui` working\compatible images.

**Comment by goldyfruit** [comment]
Just got a similar issue with tag `0.0.10`, by default the `latest` tag is tried but doesn't exist.

Here is a quick workaround to get EDA deployed.

```yaml
  image: quay.io/ansible/eda-server
  image_version: main
  image_web: quay.io/ansible/eda-ui
  image_web_version: main
```

**Comment by iwt-cmd** [comment]
> Just got a similar issue with tag `0.0.10`, by default the `latest` tag is tried but doesn't exist.
> 
> Here is a quick workaround to get EDA deployed.
> 
> ```yaml
>   image: quay.io/ansible/eda-server
>   image_version: main
>   image_web: quay.io/ansible/eda-ui
>   image_web_version: main
> ```

We ran into the same issue with 0.0.11.  The "eda-ui" repo has been updated with a "latest" tag but the "eda-server" is still missing it.  We used the "image" and "image_version" flags mentioned above as a workaround.

**Comment by kurokobo** [comment]
For both `eda-server:main` and `eda-ui:latest`, backward-incompatible changes may often occur and it causes a previously successful deployment to fail in the future.
Personally, I recommend using the more exact tags (`eda-server:sha-*******` and `eda-ui:2.4.***`) of the time of success, rather than `main` or `latest`, to ensure repeatability of deployments.

**Comment by iwt-cmd** [comment]
@kurokobo This is a great point and best practice for production but the default deployment value should probably be updated so it pulls a valid image.  Currently, the deployment template provided at the head of the project will fail and probably not a great new user experience.  I'll be happy to submit a PR with this and updates to the documentation to help clarify.

**Comment by jon-nfc** [comment]
for consistancy #161

> is the work from https://github.com/ansible/awx-operator/pull/1681#discussion_r1445694531 portable to this repo? 
>
> Although chain of build does change, it would remain the same for the release cycle as the cycle starts at "staging"
>
> this method similar to the implementation in https://github.com/ansible/awx-operator/pull/1681, would have the dev build tied to the it hash, as the "internal testing image" and the release image, which starts from "staging" as the only image existing of that version in "the wild" / released to the public

Basic flow for that implementation is as follows for the actions:

- `devel` image build, used for internal purpose like testing/debugging

- `stage` start of release cycle. builds image and tags with version. also publishes to public repository

- `promote`, product release. GH release and other actions to build dependencies/sub-modules and links components together. in this case server/ui. of significant note, uses images from stage action and does not rebuild an existing item that should have been build in the stage step

**Comment by rooftopcellist** [comment]
I agree, we should adopt the same flow as the awx-operator and the multi-arch changes in https://github.com/ansible/awx-operator/pull/1681.  I will plan to update my PR to do that tomorrow. 

The permissions needed for the bundle and catalog image repos have been added to the bot, so that is in place for when we run this for real.

**Comment by rooftopcellist** [comment]
Those changes are now up for review @jon-nfc :
* https://github.com/ansible/eda-server-operator/pull/159

I'll take time to run through the workflow tomorrow and make sure it works as expected.

**Comment by rooftopcellist** [comment]
This can be closed now that https://github.com/ansible/eda-server-operator/pull/159 has merged.  I plan to release a 1.0.0 version of the eda-server-operator tomorrow morning.  Thanks everyone!
